
version: "3"
services:
  elasticsearch-v7.15.1:
    container_name: "elasticsearch"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - logger.deprecation.level=debug
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-v7.15.1-data:/usr/share/elasticsearch/data

  kibana-v7.15.1:
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
      - "5601:5601"
    restart: always
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"

volumes:
  elasticsearch-v7.15.1-data:
    driver: local